import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Planner",
  description: "Generated by create next app",
};

const comic = localFont({
  src:'comic.ttf',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={comic.className}>{children}</body>
    </html>
  );
}
